### ISSUE TITLE
First working example -- ToDo's

### ISSUE THREAD

**Issue by willirath** [willirath/pangeo_parcels#1]
There's a first working version here:
<https://github.com/willirath/pangeo_parcels/blob/f3753e8ba94684e8e310b7667ebb9549f7f81a07/notebooks/parcels_aviso.ipynb>

I think the example shows that there is a lot to do to make Parcels natively support distributed infrastructure.  A few items:

- [ ] Make sure that non-serializable object (pointers to memory most of the time) are only created just before they are needed.

- [ ] Add a generic output interface from which we could more easily create Dask arrays.

- [ ] Make sure the `inspect` calls are done right after the definition of a Kernel.

**Comment by willirath** [comment]
>  - [ ] Add a generic output interface from which we could more easily create Dask arrays.

@erikvansebille just pointed out to me that there is a  branch [`pr/486`](https://github.com/OceanParcels/parcels/compare/master...pr/486) that introduces an explicit `.export()` method to `ParticleFile`.  This might provide a way of grabbing the Numpy arrays without IO on the workers.
